language: python
python:
- '3.4'
- '3.5'
- '3.6'
- pypy3.5
install:
- pip install .
- pip install -r requirements.txt
before_script:
    export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
    py.test
script:
     - bash lambda_deploy.sh
on:
    branch: dev